ipfs/go-graphsync

network/libp2p_impl.go

Remove an unneccessary buffer based on an upstream fix - see https://github.com/ipfs/go-bitswap/pull/103

fix(network): remove buffer

---

docs/go-graphsync.puml
go.mod
go.sum
graphsync.go
graphsync_test.go
ipldbridge/ipld_impl.go
ipldbridge/ipldbridge.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go
requestmanager/responsecollector.go
requestmanager/responsecollector_test.go
testbridge/mockbuilder.go
testbridge/mocknodes.go
testbridge/testbridge.go
testbridge/testbridge_test.go

Integrate features written so far to actually have the top level interface send a request across the network. No processing on the other side, no response.
- update all the IPLD code to match changing interfaces in go-ipld-prime
- remove special error type used in request manager
- build the top level exchange interface - GraphSync - to setup dependencies, and call the code to make a request to the network
- test that:
1. Sets up to mocknet hosts & GraphSync network for each one
2. Sets up a GraphSync exchange on one while manually reading incoming messages for the other
3. Makes a mock selector spec and initiates a request on the exchange to the other peer for that selector
4. Verifies the second peer received the message, and the selector was correctly encoded in it.
fix #6

Graphsync user can make request to the network

---

README.md

Outline public interfaces for using GraphSync for review by Filecoin stakeholders
I did this by completing an initial Readme documenting project usage so that once approved we'll also have documentation. Recommend choosing the [rich diff view](https://github.com/ipfs/go-graphsync/pull/20/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) when reviewing this PR

Proposal: Graphsync Public Interfaces

---

README.md

I think these are just typos, pretty straightforward.
Although that's not all that needs to be done:
I'm setting this stuff up for https://github.com/ipfs/go-ipfs-provider and so I'll try to get these badges working as well.

Change readme badges to point to go-graphsync

---

graphsync_test.go
responsemanager/peerresponsemanager/peerresponsesender.go
responsemanager/peerresponsemanager/peerresponsesender_test.go
responsemanager/responsebuilder/responsebuilder.go
responsemanager/responsebuilder/responsebuilder_test.go

Prevent a Graphsync responder form sending a response message that is too large for the requester to process when it receives the message
- track total block size for a given graphsync response message in the ResponseBuilder class
- buffer a new message every time we exceed the max response size (512K for now, taken from bitswap.
512k is perhaps aggressive? Not sure though. It's purely a limit on block size so messages could be larger through metadata, though my guess is we could punch it up to 2MB before we came anywhere close to the 4MB limit on the receiving side.

Limit Response Size

---

messagequeue/messagequeue.go
messagequeue/messagequeue_test.go

Remove warning log messages, but also shutdown quickly without unneccesary send attempts
Previously, we allowed the last message send attempt to run to maxRetries if the queue was shutdown, which also generated warning logs. 
Now, if a send attempt fails, check that the queue has shutdownand immediately return if it has
Adds a test to replicate the failing behavior and verify the fix resolves it -- the test does involve use of time expiry, which is non-ideal, but probably there is nothing we can do until we have a mocked time in this repo.

fix(messagequeue): no retry after queue shutdown

---

message/message.go
message/message_test.go
message/pb/message.pb.go
message/pb/message.proto
messagequeue/messagequeue_test.go
network/libp2p_impl_test.go
requestmanager/requestmanager_test.go
requestmanager/utils.go
responsemanager/responsebuilder/responsebuilder.go
responsemanager/responsebuilder/responsebuilder_test.go

Bring implementation in line with spec, specifically https://github.com/ipld/specs/pull/205
Metadata is now an extension, and further extensions will be added soon

feat(graphsync): support extension protocol

---

graphsync.go
impl/graphsync.go
impl/graphsync_test.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go

Allow Graphsync users to pass extensions data of their own in a Graphsync request.
- Add variadic args to request to allow passing an arbitrary set of extension data in a Graphsync request.
- Pass args to request manager and into outgoing graphsync request message

Send user extensions in request

---

impl/graphsync_test.go
ipldbridge/ipld_impl.go
ipldbridge/ipldbridge.go
responsemanager/responsemanager.go
responsemanager/selectorvalidator/selectorvalidator.go
responsemanager/selectorvalidator/selectorvalidator_test.go
testbridge/testbridge.go

In untrusted context, limit recursive selectors to a fixed depth to prevent some DOS attacks. (should have been done a while ago)
- When a request is received, examine the passed selector by (perhaps a bit meta) traversing the selector spec with a selector, checking all recursive selectors have a depth <= 100 (current fixed depth limit)
- Does not include customizing allowed max depth for now (future ticket)
- Does not rule out other kinds of selectors yet
- also simplifies request tracking in response manager by saving whole request instead of individual components
- also removes the BuildSelectorSpec method from IPLD bridge because it's a very thin wrapper on ipld prime that needs no mocking.

Add a default validation policy

---

docs/go-graphsync.puml
graphsync.go
impl/graphsync.go
impl/graphsync_test.go
ipldbridge/ipld_impl.go
ipldbridge/ipldbridge.go
metadata/metadata.go
responsemanager/peerresponsemanager/peerresponsesender.go
responsemanager/peerresponsemanager/peerresponsesender_test.go
responsemanager/responsebuilder/responsebuilder.go
responsemanager/responsebuilder/responsebuilder_test.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go
testbridge/mocknodes.go
testbridge/mockselector.go
testbridge/testbridge.go
testbridge/testbridge_test.go

Adds the ability to add hooks that run when processing requests
- Remove methods from IPLD bridge that don't have to do with tests
- Add methods to register response hooks
- Add processing of response hooks as part of request validation
- Add plumbing of extension data through on responses

Request hooks

---

graphsync.go
impl/graphsync.go
impl/graphsync_test.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go

Add ability to process incoming responses and halt requests as neccesary
- define interface for adding response hooks
- process response hooks when responses are received
- refactor integration tests to simplify them

Add response hooks

---

README.md

The README currently implies that one needs to implement these functions manually.

docs(readme): document the storeutil package in the readme

---

go.mod
graphsync.go
impl/graphsync_test.go
linktracker/linktracker_test.go
message/message_test.go
messagequeue/messagequeue_test.go
metadata/metadata_test.go
network/libp2p_impl_test.go
peermanager/peermanager_test.go
peermanager/peermessagemanager_test.go
requestmanager/asyncloader/asyncloader_test.go
requestmanager/asyncloader/loadattemptqueue/loadattemptqueue_test.go
requestmanager/asyncloader/responsecache/responsecache_test.go
requestmanager/asyncloader/unverifiedblockstore/unverifiedblockstore_test.go
requestmanager/loader/loader_test.go
requestmanager/requestmanager_test.go
requestmanager/responsecollector_test.go
responsemanager/loader/loader_test.go
responsemanager/peerresponsemanager/peerresponsesender_test.go
responsemanager/responsebuilder/responsebuilder_test.go
responsemanager/responsemanager_test.go
responsemanager/selectorvalidator/selectorvalidator_test.go
storeutil/storeutil_test.go
testutil/channelassertions.go
testutil/testchain.go
testutil/testnodes_test.go
testutil/testutil.go

Graphsync is big and has lots of tests. Those tests are not very easy to reach particularly because they involve a lot of tests on channels. This PR introduces Testify and a few utility functions to make the tests vastly more readable and clearer in intent.
- Introduce testify, replace standard if -> t.Fatal pattern -- means test that correct conditions are met, rather than that the opposite (incorrect conditions trigger an error) -- makes for more clear, readable code
- Clean up error messages
- Refactor a few tests to switch to simpler table test form, BDD
- Introduce channel assertion utilities. Often we are testing for the fact that a value comes in on a channel before context cancellation, or one channel produces a value before others. We often need to read the value in the process. …

Testify refactor

---

graphsync.go
impl/graphsync.go
impl/graphsync_test.go
requestmanager/requestmanager.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go
selectorvalidator/selectorvalidator.go
selectorvalidator/selectorvalidator_test.go

Some graphsync operators may want to operate a graphsync node which is more locked down, rejecting all requests by default, and only authorizing requests through hooks.
- modify hook registrations to return an unregister function (so hooks can be removed)
- setup default validation as simply a validating hook
- add a configurable functional options pattern to graphsync constructor
- add an option to reject all requests by default -- just unregisters default validation
- fix a potential race condition with list of request hooks in ResponseManager

Option to Reject requests by default

---

graphsync.go
ipldutil/ipldutil.go
requestmanager/requestmanager.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go

When extensions are present, we may want the ability to use a different blockstore, and a specialized IPLD node representation for our nodes. For example, in Filecoin, when serving chain syncing requests, we want to be able to load from the chain store as opposed to the blockstore we use for moving around pieces, and for speed, we may want to use an optimized representation fo blocks for speed.
- add passing a nodebuilderchooser to ipldutil.Traverse. If the parameter is nil, go back to the old chooser
- add setting loader and chooser on request hook actions
Note: this is the first of two tickets -- the second will be adding hooks to do this on the other side for outgoing requests.

Support custom loader and nodebuilderchooser through hooks

---

.golangci.yml
graphsync.go
impl/graphsync.go
impl/graphsync_test.go
requestmanager/asyncloader/asyncloader.go
requestmanager/asyncloader/asyncloader_test.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go
selectorvalidator/selectorvalidator.go
testutil/chaintypes/gen/main.go
testutil/chaintypes/testchain_gen.go
testutil/chaintypes/testchain_minima.go
testutil/testchain.go

Background on the needs here:
- There's a strong need in the filecoin ecosystem to be able to swap out blockstores for certain types of requests
- One of the key paths to optimizing graphsync performance is to be able to use special ipld node types (code-gen'd) for specific use cases
This builds on the previous addition of swapping the loader and node-builder-chooser on the response side with similar hooks on the request side. Because the request side has to deal with storing as well as  loading, and in order to not end up with duplicate store operations, I've decided to uniquely identify loader/storer combos as alternate persistence options, distinguished by a unique string name. (toyed with trying to not require the string name, but as you know, go is not good with comparability in …

Outgoing Request Hooks, swapping persistence layers

---

graphsync.go
impl/graphsync.go
impl/graphsync_test.go
responsemanager/hooks/completedlisteners.go
responsemanager/peerresponsemanager/peerresponsesender.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go

Provide a way for graphsync user to determine when it finishes responding to a received request
- Add one last hook -- this time just a listener -- that gets called on the responder side when we finish responding to requests
- modify PeerResponseSender to provide correct response status information for completed requests

feat(responsemanager): add listener for completed responses

---

go.mod
go.sum
requestmanager/hooks/requesthooks.go
requestmanager/hooks/responsehooks.go
responsemanager/hooks/blockhooks.go
responsemanager/hooks/completedlisteners.go
responsemanager/hooks/requesthook.go
responsemanager/hooks/requestupdatehooks.go

Reduce copy-pasta around setting up subscriptions, avoid accidental mutex errors with subscription lists
- use a little library https://github.com/hannahhoward/go-pubsub that implements this functionality in a generic way
- remove non-specific logic from all the hooks.
- also using this pattern in go-data-transfer, go-fil-markets in filecoin ecosystem, repo can move into PL namespace if someone is willing to own it (it's not functionality that is particularly IPFS-ey or Filecoin-ey)

Use external pubsub

---

responsemanager/responsemanager.go

MInor: add nil check for an empty task (task deleted but not finished removing from peer task queue)

fix(responsemanager): add nil check

---

graphsync.go
impl/graphsync.go
impl/graphsync_test.go
requestmanager/asyncloader/asyncloader.go
requestmanager/asyncloader/loadattemptqueue/loadattemptqueue.go
requestmanager/asyncloader/loadattemptqueue/loadattemptqueue_test.go
requestmanager/hooks/blockhooks.go
requestmanager/hooks/hooks_test.go
requestmanager/hooks/responsehooks.go
requestmanager/loader/loader.go
requestmanager/loader/loader_test.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go
requestmanager/types/data.go
responsemanager/hooks/hooks_test.go
responsemanager/peerresponsemanager/peerresponsesender.go
responsemanager/peerresponsemanager/peerresponsesender_test.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go
testutil/testutil.go

Provide a mechanism to execute hooks on the client side as each block is successfully verified and loaded
- Define block hook interfaces
- Modify AsyncLoadResult to identify if request was loaded from local blockstore or from response from network
- Add block hooks infrastructure to requestmanager side -- using same pubsub interface
- Add block hook processing to the request manager & its loader. What this looks like is:
- Add an extra parameter to the wrapped async loader to run a block hook on each successfully loaded block
- Refactor setup request to seperate request validation and request processing
- add an atomic.Value to each inProgressRequestStatus to track the last response received
- add code to update last response received
- when each block is loaded, the block hook function …

Incoming Block Hooks

---

cidset/cidset.go
cidset/cidset_test.go
impl/graphsync_test.go
responsemanager/peerresponsemanager/peerresponsesender.go
responsemanager/peerresponsemanager/peerresponsesender_test.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go

Provide responder side implementation of https://github.com/ipld/specs/blob/master/block-layer/graphsync/known_extensions.md#do-not-send-cids
- add functionality to peerResponseSender to preload links into the link tracker so blocks aren't sent
- add decode/encode functionality to/from specified cbor-encoded IPLD structure for cid.Set
- add code to process extension and pass links on to peerResponseSender in ResponseManager

Implement do-no-send-cids extension

---

impl/graphsync_test.go
ipldutil/ipldutil.go
requestmanager/executor/executor.go
requestmanager/loader/loader.go
requestmanager/loader/loader_test.go
requestmanager/requestmanager.go
requestmanager/utils.go
responsemanager/runtraversal/runtraversal.go
responsemanager/runtraversal/runtraversal_test.go

In preparation for adding pause/resume to the request side of graphsync, refactor some code into a request "executor module". Also properly implement skipping parts of the tree that are missing -- at the time we originally wrote graphsync, IPLD selectors had not abilty to "skip" on block load errors but now they have this ability.
- extract code that runs in a go routine for request execution to its own module
- also removes need for a seperate networkErrorChannel
- remove visitToChannel function
- Properly use IPLD SkipMe's so we can complete graphsync requests where provider is missing some branches

Refactor request execution and use IPLD SkipMe functionality for proper partial results on a request

---

graphsync.go
impl/graphsync.go
responsemanager/queryexecutor.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go

Allow users of module (particularly those listening through hooks) to have more fine grained control of responding to requests
- Add ability to pause response imperatively if you know the request ID
- Add ability to cancel response imperatively
- Add ability to send extensions when resuming a response (may want to include information about why it was resumed
- Refactor out query execution code from response manager (just a simple struct extraction for now -- not putting it in a seperate module at the moment)

More fine grained response controls

---

graphsync.go
impl/graphsync.go
impl/graphsync_test.go
responsemanager/hooks/completehooks.go
responsemanager/hooks/hooks_test.go
responsemanager/queryexecutor.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go

add the ability to send extensions with a final message
- Add hookactions for complete
- Support sending extension data along with complete response

add extensions on complete

---

requestmanager/requestmanager.go
requestmanager/requestmanager_test.go

We should run response hooks even on requests that are already completed

Run response hooks on completed requests

---

message/pb/message.pb.go

Fix potential overflow errors in unmarshal code for protobuf messages
And older version of gogo-protobuf had generated our message.pb.go code which was lacking checks for negative indexes due to integer overflow issues.
I installed the latest version of protoc-gen-gogofaster (the version we use) and regenerated to get these changes, which insert checks for negative values.

fix(message): regen protobuf code

---

graphsync.go
impl/graphsync.go
requestmanager/asyncloader/asyncloader.go
requestmanager/asyncloader/asyncloader_test.go
responsemanager/persistenceoptions/persistenceoptions.go

add unregister ability to persistence options so we can create short lived options for single
requests

feat(persistenceoptions): add unregister ability

---

dedupkey/dedupkey.go
graphsync.go
impl/graphsync_test.go
linktracker/linktracker.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go
responsemanager/peerresponsemanager/peerresponsesender.go
responsemanager/peerresponsemanager/peerresponsesender_test.go
responsemanager/queryexecutor.go
responsemanager/responsemanager_test.go

- provide a way to communicate that you don't want requests deduplicated across blocks
When you register alternate persistence stores, it's important to treat requests to those persistence stores as if they are a seperate peer.
This impliments a "dedup by key" extension which provides a way to say to a provider, for this peer, only dedup blocks in requests that also have this key.
On the provider, we simply use the alternate store name as the key

Dedup by key extension

---

graphsync.go
requestmanager/requestmanager_test.go
requestmanager/responsecollector.go

As discussed, if the user's request context is cancelled for whatever reason, we should write that error to the reponse error channel.
@hannahhoward Because we ignore context cancellation errors here:
https://github.com/ipfs/go-graphsync/blob/d88611c4c9698f8f72daf31f64908c52d8f42d24/requestmanager/executor/executor.go#L148
we had a race wherein we'd mark a request as "completed" even though the context is cancelled because we close the response error channel here without writing anything to it. Have fixed that as well.
LMKWYT.

Return Request context cancelled error

---

selectorvalidator/selectorvalidator.go

Selector validator is a continous source of memory leaks cause it constructs the same selector over and over
Do not reconstruct a complicated selector on each call to selector validate -- put it in the init for the module.

Memory optimization in selector validator

---

benchmarks/benchmark_test.go
requestmanager/asyncloader/responsecache/responsecache.go
requestmanager/asyncloader/responsecache/responsecache_test.go
requestmanager/asyncloader/unverifiedblockstore/unverifiedblockstore.go

We've witnessed high CPU usage in UnverifiedBlockStore.PruneBlocks in the wild. Prune blocks is used to make sure that blocks received from a remote peer for a traversal do not accumulate in memory. This happens at two points:
1. If they appear in a message, but are not attached to metadata for a response in the message, they are pruned.
2. If a response terminates without the traversal consuming the block, they are pruned
The problem here is that when we do #1, which is run after every message received, we currently loop through all blocks in the store -- meaning that if they were part of a previous message and didn't get pruned cause they were referenced in metadata, but the selector traversal hasn't caught up and removed the block from the store, we still iterate over them blocks.
For …

Prune blocks more intelligently

---

graphsync.go
impl/graphsync.go
impl/graphsync_test.go
messagequeue/messagequeue.go
messagequeue/messagequeue_test.go
notifications/mappable.go
notifications/notifications_test.go
notifications/publisher.go
notifications/types.go
peermanager/peermessagemanager.go
peermanager/peermessagemanager_test.go
requestmanager/executor/executor.go
requestmanager/executor/executor_test.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go
responsemanager/hooks/listeners.go
responsemanager/peerresponsemanager/peerresponsesender.go
responsemanager/peerresponsemanager/peerresponsesender_test.go
responsemanager/queryexecutor.go
responsemanager/responsebuilder/responsebuilder.go
responsemanager/responsebuilder/responsebuilder_test.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go
responsemanager/subscriber.go
testutil/testnotifications.go

Provide a way on the responding side to know how much data has gone over the wire and to know when actual network errors occur
Essentially, or goal here is a pub-sub system to escalate asyncronous notifications back through the chain of callers to provide information to the response manager about what actually happened with data it attempted to send over the wire
- build a simple pub/sub topic system, with with a key feature -- the ability to remap topics -- I subscribe on one topic but receive notifications on another
- in the message queue, publish notifications when things happen with a message: it's queued, it's successfully sent, or an error occurs
- the the peer response sender use the queue event to insure one messages is processed at a time, and republish response sender events …

Track actual network operations in a response

---

CHANGELOG.md
messagequeue/messagequeue.go
responsemanager/subscriber.go
testutil/testnotifications.go

update for 0.3.0 + style fixes

feat(CHANGELOG): update for 0.3.0

---

benchmarks/benchmark_test.go
messagequeue/messagequeue.go
messagequeue/messagequeue_test.go
notifications/notifications_test.go
notifications/publisher.go
notifications/types.go
responsemanager/peerresponsemanager/peerresponsesender.go

Resolve go routine leak for notifications publishers
- write a benchmark that simulates the conditions where we are seeing this go routine leak
- add a Startup() method to the publisher and don't start go routine automatically (not essential but generally we try not to start go-routines in constructors
- call Shutdown() on the publisher whenever the module using it shuts down (MessageQueue & PeerResponseSender)
Benchmark results before:
```
go test -v -bench=BenchmarkRoundtripSuccess/test-repeated-disconnects-20-10000$ --memprofile=profile.out --cpuprofile=cpu.out
goos: darwin
goarch: amd64
pkg: github.com/ipfs/go-graphsync/benchmarks
BenchmarkRoundtripSuccess
BenchmarkRoundtripSuccess/test-repeated-disconnects-20-10000
benchmark_test.go:130: Number of running go-routines: 866 …
```

Shutdown notifications go routines

---

benchmarks/benchmark_test.go
benchmarks/testinstance/testinstance.go
go.mod
go.sum
impl/graphsync.go
responsemanager/allocator/allocator.go
responsemanager/allocator/allocator_test.go
responsemanager/peerresponsemanager/peerresponsesender.go
responsemanager/peerresponsemanager/peerresponsesender_test.go

With slow receiving peers, we can sometimes make major memory allocators in a selector traversal if the blocks we're traversing aren't being sent. We would like to slow down traversals with backpressure to prevent global allocations from going over a certain amount
- Establish an allocator that will allocate and deallocate, against both a global total and a per peer total. The allocate command returns a channel when the allocation can be safely completed under both the global and per peer max (if it can be done currently under the global and per peer max the channel will read immediately)
- When deallocating, prioritize in the following order:
- peers where pending next allocation will go under per peer max for that peer
- if there are multiple that meet this criteria, prioritize peer …

Add allocator for memory backpressure

---

notifications/publisher.go

To support shutdowns of the publisher we have a lock and channel check on every method of publisher. However, for Close we forgot... and this did lead to a lock.
add check if publisher is shutdown to Close method

fix(notifications): fix lock in close

---

go.mod
message/message.go
requestmanager/asyncloader/unverifiedblockstore/unverifiedblockstore.go
storeutil/storeutil.go

Remove some unneccesary mem copies identified in testing. Specifically:
- The `go-ipld-prime` Storer interface has an unneccesary copy of block bytes due to the need to create a bytes.Buffer to mimic an io.Writer. This creates a shortcut around that and implements it by default for the StorerFromBlockstore method
- When we switched to google's protobuf library, we didn't implement logic to avoid temporary buffers when writing protobuff message. This implements that using go-buffer-bool (similar to go-bitswap)

Improve memory usage

---

impl/graphsync.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go

Currently we set a hard maximum of processing a maximum of six responses at once concurrently. In situations where we have alternate DDOS protection (such as rejecting responses by default without authentication), we may want to be able raise that value. This PR allows configuration for the maximum simultaneous responses at once.
- Provide a configuration option to change the maximum number of requests processed at once by the
responder

Allow configuration of max simultaneous responses

---

impl/graphsync.go
impl/graphsync_test.go
listeners/listeners.go
requestmanager/executor/executor.go
requestmanager/executor/executor_test.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go
responsemanager/responsemanager_test.go

Fixes https://github.com/ipfs/go-graphsync/issues/124
This PR adds a test case, and a WIP implementation.
@hannahhoward I'm not sure if the implementation follows the pattern for how these cases are normally handled to feel free to change.

RegisterNetworkErrorListener should fire when there's an error connecting to the peer

---

CHANGELOG.md
impl/graphsync_test.go
notifications/data_subscriber.go
notifications/types.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go
responsemanager/peerresponsemanager/peerresponsesender.go
testutil/testnotifications.go

docs(CHANGELOG): update for v0.5.2

---

messagequeue/messagequeue.go
notifications/data_subscriber.go
peermanager/peermanager.go
responsemanager/peerresponsemanager/peerresponsesender.go
responsemanager/queryexecutor.go

I set out make TestNetworkDisconnect integration test reliable, and in the process identified several race conditions and issues related to network disconnects
Testing and debugging identified 4 distinct problems, whose fixes are contained in this PR:
1. When a MessageQueue or PeerResponseSender is shut down due to disconnect, it may have outgoing messages that won't otherwise be processed -- we need to propagate network errors for these messages, since they will never be sent.
2. When we implemented https://github.com/ipfs/go-graphsync/pull/128, we introduced a bug where if a topic on a data subscriber is closed, we retain the mappings. If the same topic is later reopened (due to say, a new message queue being instantiated), the old subscribers would get messages. Now we clear mappings …

Fix network error propagation

---

benchmarks/testnet/network_test.go
graphsync.go
impl/graphsync.go
impl/graphsync_test.go
listeners/listeners.go
network/interface.go
network/libp2p_impl.go
network/libp2p_impl_test.go

fix #129 
- Add new RegisterReceiveNetworkErrorListener hook
- Modify ReceiveError method on network interface to pass peer
- Call ReceiverNetworkErrorListeners in ReceiveError callback

Add error listener on receiver

---

impl/graphsync.go
messagequeue/messagequeue.go
messagequeue/messagequeue_test.go
responsemanager/queryexecutor.go
responsemanager/responseassembler/peerresponsebuilder_test.go
responsemanager/responseassembler/responseassembler.go
responsemanager/responseassembler/responseassembler_test.go
responsemanager/responseassembler/transactionBuilder.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go

In this PR:
- Rename cleanups
- A bit more docs
More importantly:
- Moving the large block message breakup test over to message queue (since that is where that logic lives now)
- This actually revealed an actual bug in the refactor (see change to messagequeue.go)

Additional changes to response assembler refactor

---

impl/graphsync.go
messagequeue/messagequeue.go
messagequeue/messagequeue_test.go
peermanager/peermessagemanager.go
peermanager/peermessagemanager_test.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go
responsemanager/responseassembler/responseassembler.go
responsemanager/responseassembler/responseassembler_test.go

Currently block allocation is split between allocation in the response builder and release in the message queue. This works, but only if the components cooperate, and it is fragile in the long term. The PR brings allocation and release into the  message queue.
* Add a context.Context to the BuildMessage function (in all interfaces and implementations)
* Add the AllocateBlockMemory function to the MessageQueue Allocator interface.
* Move the delay logic from ResponseAssembler.execute to MessageQueue.AllocateAndBuildMessage and remove the ResponseAssembler Allocator interface.
* Document the possible block in AllocateAndBuildMessage functions.

move block allocation into message queue

---

testplans/graphsync/go.mod
testplans/graphsync/main.go
testplans/graphsync/manifest.toml

Provide a mechanism to compare graphsync against HTTP.
Adds setup of HTTP to the default testplan. Can be turned on and off. Default is on.

Add optional HTTP comparison

---

testplans/graphsync/README.md
testplans/graphsync/go.mod
testplans/graphsync/go.sum
testplans/graphsync/main.go
testplans/graphsync/manifest.toml

Add some final parameters and diagnostics to the graphsync testplan, and document exactly what all the parameters do
- Add a parameter that turns the http comparison into a libp2p over http comparison
- Add a parameter that allows you to configure graphsync's maximum number of simultaneous requests the responder will process (this is something passed to the constructor of graphsync)
- Add block diagnostics - enables precise loggings of time it takes to get to each block (block queued & block sent on responder, response received and blocked processed on the requestor)
- There are a lot of parameters, so add a README that lays out all the possible parameters you can mess with and explanations for why you might want to change some of them.

Round out diagnostic parameters

---

CHANGELOG.md

- github.com/ipfs/go-graphsync:
- Better logging for Graphsync traversal (#167) ([ipfs/go-graphsync#167](https://github.com/ipfs/go-graphsync/pull/167))
Contributors
| Contributor | Commits | Lines ± | Files Changed |
|-------------|---------|---------|---------------|
| Aarsh Shah | 1 | +18/-2 | 2 |

release v0.6.2

---

graphsync.go
impl/graphsync.go
responsemanager/hooks/requesthook.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go

We want to debug issues where transfers get delayed because requests spend too much time on the queue. The current request receieved hook is fired AFTER the GS request is popped off from the responder's queue.
We need a hook that is fired when the gs request is pushed to the queue.

[WIP Draft] Request Queued hook

---

go.mod
impl/graphsync.go
messagequeue/messagequeue.go
network/libp2p_impl.go
requestmanager/asyncloader/responsecache/responsecache.go
requestmanager/requestmanager.go
responsemanager/queryexecutor.go
responsemanager/querypreparer.go
responsemanager/responseassembler/responseBuilder.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go

fix #175
This builds of #176 but avoids moving hooks around in terms of timing in any substantive way. Rather, it cleans up hook processing to insure that request hooks are processed only on the main response manager thread, so that there aren't races with any calls made during hook processing.

Resolve 175 race condition, no change to hook timing

---

requestmanager/requestmanager.go

Improve logging by recording graphsync request timings
Log total time recorded for each graphsync request via start and end.

feat(requestmanager): add request timing

---

graphsync.go
impl/graphsync.go
impl/graphsync_test.go
ipldutil/traverser.go
ipldutil/traverser_test.go
requestmanager/executor/executor.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go
requestmanager/responsecollector.go

Add an imperative method that cancels a graphsync request and does not return until no further blocks can load and the request is completely cleaned up
- Add top level CancelRequest method
- Add requestmanager CancelRequest method
- CancelRequest
- cancels the internal request context (this will trigger running request routines to terminate)
- sends a cancellation to the other peer
- waits for any processing to complete by adding a notfication channel that gets written only when all processing is complete for the request
- sending RequestClientCancelledErr (formerly RequestContextCancelledErr)
- rename poorly named private var "network error" to "terminal error"
- protect against multiple terminal errors by only writing once
- Fix race in IPLD util traversal
- Rename …

Add cancel request and wait function

---

impl/graphsync.go
requestmanager/executor/executor.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go

Make any customizations of the linksystem passed to Graphsync apply to the RequestManager (such as NodeReifier) -- this means if UnixFS reification is enabled on both sides you can do a directory path based selector query in Graphsync
Pass through the supplied linksystem down through the RequestManager to the underlying traverser.

Pass through linksystem

---

message/message.go
responsemanager/queryexecutor.go
responsemanager/querypreparer.go
responsemanager/responsemanager_test.go
responsemanager/runtraversal/runtraversal.go

Enforce returning error codes that more closely match the graphsync spec
- Make sure requests that are not validated return ResponseRejected
- Make sure requests that fail to load first block return RequestFailedContentNotFound
- Fix inconsistencies in value given to CompletedResponseListener vs returned in request
- Add ResponseRejected to IsTerminalResponseCode (should have been there before)
- Enforce more specific response code tests in tests of the response manager

Fix error codes

---

graphsync.go
requestmanager/requestmanager.go

Allows the caller to ignore a "request not found" error, for example when shutting down graphsync

replace particular request not found errors with public error

---

allocator/allocator.go
allocator/allocator_test.go
benchmarks/testinstance/testinstance.go
go.mod
go.sum
graphsync.go
impl/graphsync_test.go
ipldutil/ipldutil.go
ipldutil/traverser.go
ipldutil/traverser_test.go
messagequeue/messagequeue.go
requestmanager/asyncloader/asyncloader.go
requestmanager/asyncloader/asyncloader_test.go
requestmanager/asyncloader/responsecache/responsecache.go
requestmanager/asyncloader/unverifiedblockstore/unverifiedblockstore.go
requestmanager/requestmanager.go
responsemanager/responsemanager.go
storeutil/storeutil.go
testutil/chaintypes/ipldsch_satisfaction.go
testutil/testnodes_test.go

Fix all go vet / staticcheck errors
- updated go-ipld-prime to latest get code gen that does not have go vet errors
- mean we had to change one test due to a traversal order effect from now properly sorting map fields for DAG-JSON / DAG-CBOR
- re-codegen sections to resolve `go vet` Unkeyed fields errors
- resolve all static check issues
- remove one unneeded wrapper method
go-graphsync has some unreliable tests on Circle-CI, and I'm sure those will be accentuated when we switch over to Universal CI, as they were with go-bitswap. So we'll need to do seperate work there.

Ready for universal CI

---

CHANGELOG.md
go.mod
graphsync.go
impl/graphsync.go
impl/graphsync_test.go
ipldutil/traverser.go
ipldutil/traverser_test.go
message/message.go
messagequeue/messagequeue.go
network/libp2p_impl.go
requestmanager/asyncloader/responsecache/responsecache.go
requestmanager/executor/executor.go
requestmanager/requestmanager.go
requestmanager/requestmanager_test.go
requestmanager/responsecollector.go
requestmanager/responsecollector_test.go
responsemanager/hooks/requesthook.go
responsemanager/queryexecutor.go
responsemanager/querypreparer.go
responsemanager/responseassembler/responseBuilder.go
responsemanager/responsemanager.go
responsemanager/responsemanager_test.go
responsemanager/runtraversal/runtraversal.go
responsemanager/runtraversal/runtraversal_test.go
scripts/mkreleaselog

Merge 0.6.x branch, even though it may get a few more commits
Merge, fix conflicts (several cause of linksystem)

Merge the v0.6.x commit history

---

requestmanager/asyncloader/unverifiedblockstore/unverifiedblockstore.go

To debug https://github.com/filecoin-project/lotus/issues/7077.

Log unverified blockstore memory consumption

---

message/builder.go
message/builder_test.go

If a response is built with extensions but NO other data, it can get dropped, because of a bug where we're not marking an outgoing response needing to get sent. This is most likely to happen when there are multiple responses being sent between the same requestor and responder.
Note: we should refactor this builder code cause I think it's weird that we're determining responses based on who has metadata. That being said, best to get this fixed for now.

P0 Bug: Dropping extensions in response messages

---

allocator/allocator.go

Add debug logs to track behavior of allocator to check for errors
This will make an already chatty graphsync debug log even  more chatty but seems worth it

Add debug logging to allocator

---

impl/graphsync.go
requestmanager/asyncloader/asyncloader.go
requestmanager/asyncloader/asyncloader_test.go
requestmanager/requestmanager.go
requestmanager/testloader/asyncloader.go

When memory backpressure for requests was introduced, it was introduced in such a way that not only blocks processing of further libp2p messages, but also blocks the main thread of the request manager. This may have serious side effects, as this effectively can cause the request manager to sieze up and not processing other commands like cancelling requests.
Move potentially blocking memory allocation out of the main AsyncLoader & the internals of the main RequestManager thread, and into the per-peer thread of the libp2p message handler. This has the same effect of blocking reading further libp2p messages on the stream, and preserving memory, while at the same time not blocking the request manager thread.
Also removes parameter from AsyncLoader.ProcessResponses that is now spurious.

Remove main thread block on allocation

---

impl/graphsync.go
impl/graphsync_test.go
requestmanager/client.go
requestmanager/executor/executor.go
requestmanager/executor/executor_test.go
requestmanager/messages.go
requestmanager/requestmanager_test.go
requestmanager/server.go
taskqueue/taskqueue.go
testutil/testutil.go

implement #215 
This is not a super simple PR as adding request limits required some sizable lifting to the request manager operations.
Here are the substantive changes:
- Use a PeerTaskQueue to handle rate limiting and request distribution
- I find myself writing the worker function to consume a PeerTaskQueue over and over... so I wrote an abstraction to do it. And actually, this is useful cause we can make it an interface and implement other versions -- like an execute immediately, or maybe one that scales with demand, or handles multiple types of tasks, or distributes different requests to different queues... who knows!
- Refactor the executor to simply execute a single request till it pauses or finishes. I've removed the "resume" code from the executor which makes it much simpler -- …

Add request limits

---

graphsync.go
requestmanager/asyncloader/responsecache/responsecache.go

Support for https://github.com/filecoin-project/lotus/issues/7227 by making missing blocks identifiable as an error
- Define an error type for missing blocks
- Use it

Give missing blocks a named error

---

responsemanager/responsemanager_test.go

Fix #193 
The root problem is this test is testing something not gauranteed to happen, even when response manager behaves correctly.
Essentially, when a network send error occurs, we want to interrupt execution of a response.. However, it is still possible
the execution of the selector query is already complete, even if there are still blocks waiting to be sent over the network. In this case, there will not be any clearing of the request. That's ok.

Remove assertion with gauranteed flaky behavior

---

benchmarks/testnet/virtual.go
graphsync.go
impl/graphsync.go
network/interface.go
network/libp2p_impl.go
requestmanager/client.go
requestmanager/requestmanager_test.go
requestmanager/server.go
responsemanager/client.go
responsemanager/queryexecutor.go
responsemanager/responsemanager_test.go
responsemanager/server.go
responsemanager/subscriber.go
testutil/testconnmanager.go

Protect libp2p connections in go-graphsync. fix #226
- Add ConnManager to network interface
- In both RequestManager and ResponseManager, protect the connection at the time the request is queued, and release the connection when the request terminates
- Protect by RequestID so that protections are unique to request
- Modify ResponseManager to use state pattern from RequestManager -- this corrects a bug discovered in failure to cleanup request when cancelled before it starts executing.

Protect Libp2p Connections

---

donotsendfirstblocks/donotsendfirstblocks.go
graphsync.go
impl/graphsync_test.go
responsemanager/client.go
responsemanager/querypreparer.go
responsemanager/responseassembler/peerlinktracker.go
responsemanager/responseassembler/responseBuilder.go
responsemanager/responseassembler/responseassembler.go
responsemanager/responseassembler/responseassembler_test.go
responsemanager/responsemanager_test.go

Implement #225
- add the extension name an a utility to encode decode the data (just a number)
- add processing of the extension to the query preparer
- handle behavior for the extension in the response assembler. You can now specify a number of blocks (** non-unique **) on a request to traverse before they start going over the wire.
- add integration test to demonstrate flow

Do not send first blocks extension

---

graphsync.go
impl/graphsync_test.go
requestmanager/executor/executor.go
responsemanager/responseassembler/peerlinktracker.go
responsemanager/responseassembler/responseBuilder.go
responsemanager/responsemanager_test.go
testutil/testutil.go

Make it easier to tell how many blocks have been traversed
- Add an Index() value for block data
- Set it for blocks pays to Incoming and Outgoing block hooks.

Add an index for blocks in the on new block hooks

---

go.mod
go.sum
impl/graphsync.go
impl/graphsync_test.go
ipldutil/traverser.go
ipldutil/traverser_test.go
requestmanager/client.go
requestmanager/requestmanager_test.go
requestmanager/server.go
responsemanager/client.go
responsemanager/querypreparer.go
responsemanager/responsemanager_test.go
responsemanager/server.go
testutil/testutil.go

Provide absolute limits on links traversed for incoming and outgoing requests
- use budget in Traverser utility (add logic to handle budget for first link load)
- create options for MaxLinksPerOutgoingRequest & MaxLinksPerIncomingRequest
- pass through and create traversak budgets as needed (0 vals = no max links)
- add integration tests & unit tests of traverser behavior

Add support for IPLD prime's budgets feature in selectors

---

CHANGELOG.md

- github.com/ipfs/go-graphsync:
- feat: update to go-ipld-prime v0.12.3 (#237) ([ipfs/go-graphsync#237](https://github.com/ipfs/go-graphsync/pull/237))
- Add support for IPLD prime's budgets feature in selectors (#235) ([ipfs/go-graphsync#235](https://github.com/ipfs/go-graphsync/pull/235))
- feat(graphsync): add an index for blocks in the on new block hook (#234) ([ipfs/go-graphsync#234](https://github.com/ipfs/go-graphsync/pull/234))
- Do not send first blocks extension (#230) ([ipfs/go-graphsync#230](https://github.com/ipfs/go-graphsync/pull/230))
- Protect Libp2p Connections (#229) ([ipfs/go-graphsync#229](https://github.com/ipfs/go-graphsync/pull/229))
- test(responsemanager): remove check (#228) ([ipfs/go-graphsync#228](https://github.com/ipfs/go-graphsync/pull/228))
- …

release: v1.10.0

---

responsemanager/responsemanager_test.go

TestCancellationViaCommand contained a race condition that would cause the response to sometimes finish processing before it could be cancelled.
Setup a block hook to hold processing of the response till the CancelResponse call is issued, unblock once command is issued

Fix flakiness TestCancellationViaCommand

---

go.mod
go.sum
impl/graphsync.go

Don't let the request queue fill all the way up with requests with a very slow peer in an Estuary like scenario
I didn't even know this existed in the peer task queue! What this option does is you just won't be able to pop work from a queue until the number active requests drops. Note that paused requests are not part of the active count, so we don't need to worry about that part.

Limit simultaneous incoming requests on a per peer basis

---

benchmarks/testnet/virtual.go
impl/graphsync.go
messagequeue/messagequeue.go
messagequeue/messagequeue_test.go
network/interface.go
network/libp2p_impl.go

Currently, for each network message, graphsync attempts to send it for 10 minutes, then if it fails, retries 10 times. So for a network message to truly fail, it takes 100 minutes. This seems like an extremely long time.
- Copy over some network layer configuration code from go-bitswap
- Allow configuring these values. For the time being, I'm not changing the defaults -- it seems like it would be better to experiment in the estuary context and then see if there are clear correct winners for what we should do here.

Configure message parameters

---

allocator/allocator.go
allocator/allocator_test.go

Address scenario that could cause an underflow in the allocator (leading to total allocated
being very high)
The scenario is:
- peer 1 allocates block amount x
- peer 2 allocates block amount y >= 1
- peer 1 call to deallocate block amount x+1 (this shouldn't happen somehow it does). We protect against peer 1 allocation going below zero by setting it to 0, but the global total is now :   y-1 (x+y - (x+1))
- peer 2 deallocates entirely. total is now -1 (no check of total allocated >= 0 after peer deallocation). on unsigned int this becomes MaxUint64
- Add test to demonstrate issues
- Add precautionary check on peer deallocations to prevent underflow
- When deallocating blocks that are greater than total peer memory, only subtract total peer memory from global total, since that's what is …

Prevent allocator underflow

---

graphsync.go
impl/graphsync.go
listeners/listeners.go
requestmanager/client.go
requestmanager/requestmanager_test.go
requestmanager/server.go

Outgoing requests are now asynchronous, so a new OutgoingRequeustProcessingListener can inform a caller when the request is actually made.
Closes: https://github.com/ipfs/go-graphsync/issues/231
I'm actually not sure what the use-case is here, why might an application want to get this close to the request @hannahhoward?

feat(requestmanager): add OutgoingRequeustProcessingListener

---

responsemanager/responseassembler/responseBuilder.go

We pass one a "Block" interface for subscribers for BlockQueued and BlockSent hooks. The interface has no access to the data, but right now we hold a reference the raw block data in the implementing struct, and use it to calculate values. There's no need for this and ... eek... this could be a huge memory leak vector. It would also explain partly why we've had trouble replicating memory leaks in testplans -- it would be dependent on the behavior of the subscriber.
Anyway, can't hurt, and defensive programming

Remove vector for memory leak

---

impl/graphsync.go
responsemanager/client.go
responsemanager/messages.go
responsemanager/queryexecutor/queryexecutor.go
responsemanager/queryexecutor/queryexecutor_test.go
responsemanager/querypreparer.go
responsemanager/responseassembler/responseassembler.go
responsemanager/responsemanager_test.go
responsemanager/server.go

Builds on #263, mainly to deal with the tests in #244 that were rebased into that branch that are currently broken. But I've also been iteratively improving the state of the tests so they're a bit more readable and organised. Not perfect, but much better than in #244 so far I think.
Still needs a bit more coverage in runtraversal, since the existing runtraversal tests are not ported in the merge.

chore(queryexecutor): fix tests for runtraversal refactor + clean up

---

allocator/allocator_test.go
impl/graphsync_test.go
ipldutil/traverser_test.go
requestmanager/asyncloader/asyncloader_test.go
requestmanager/requestmanager_test.go
requestmanager/testloader/asyncloader.go
responsemanager/queryexecutor/queryexecutor_test.go
responsemanager/responseassembler/responseassembler_test.go
responsemanager/responsemanager_test.go
testutil/channelassertions.go
testutil/testchain.go
testutil/testconnmanager.go
testutil/testnotifications.go
testutil/testutil.go

mark all test helper funcs via t.Helper

---

responsemanager/client.go
responsemanager/messages.go
responsemanager/responsemanager_test.go

@rvagg I believe your WaitForNoActiveTasks was just one small concurrency fix away from being the solution. The issue here is that FinishTask is currently an asynchronous call -- it simply sends the finish message to the response manager and moves on. That means the worker queue can finish draining before the response manager thread actually processes the finish message.
The easy solution, or at least the proof of concept solution, is simply to make the FinishTask method synchronous - it doesn't return till the message is processed (this is done by using a return channel).

Fix flaky tests

---

impl/graphsync_test.go

Attempting to deal with Windows timeouts, such as @ https://github.com/ipfs/go-graphsync/runs/4374949739?check_suite_focus=true

fix(test): increase 1s timeouts to 2s for slow CI

---

taskqueue/taskqueue.go

Based on feedback from #284, I think this is closer to what I want. While we currently don't have use for >1 consumer, I want `WaitForNoActiveTasks()` to be a general, and potentially (or at least safely) multi-consumer blocking call that doesn't return until there are zero active tasks.

fix: use sync.Cond to handle no-task blocking wait

---

responsemanager/client.go
responsemanager/server.go

These are somewhat analogous to tracing work but we already have comparable lines in the request manager and it feels reasonable to have this, since they've already proven useful there :)

Add a bit of logging

---

impl/graphsync.go

@hannahhoward I noticed this when looking at some new traces I'm starting from `ReceiveMessage`. The majority that come in through here don't have any requests, so going into `responseManager.ProcessRequests` gets it put into the message handling loop and eventually hit a `for` loop that iterates over an empty slice and does nothing else. On the other side, `requestManager.ProcessResponses` has the same thing but even more branches where it hits various `for` loops to collect and process things over an empty slice when there's no responses or blocks.
So, minor optimisation, but seems to be worthwhile given how chatty this call seems to be.

chore: short-circuit unnecessary message processing

---

impl/graphsync.go
taskqueue/taskqueue.go

Well, I guess this is the price you pay for not having testing on stats! we broke the request queue stats when we did the request queue refactor
- Remove peer task queue legacy struct member
- Use responseQueue for stats instead
- Also noticed we broke peer peer limits for the responder here.

Remove accidental legacy field, fix metrics

---

impl/graphsync_test.go
message/message.go
requestmanager/executor/executor.go
responsemanager/client.go
responsemanager/messages.go
responsemanager/queryexecutor/queryexecutor.go
responsemanager/responsemanager_test.go
responsemanager/server.go
testutil/tracing.go

This works so far for the `responseManager.ProcessRequests()` path, but it's pretty complicated; with the two main problems (building on from what I mentioned @ https://github.com/ipfs/go-graphsync/pull/290/files#r760950285 about the branching inside `GraphSync#ReceiveMessage()` and wanting to have a base span that lives for the entirety of an incoming message there:
* Even if taking the `responseManager` path in isolation, each "message" can have multiple requests, each of which becomes detached from the others for processing—so making a "message" span live across all of these is going to have to take some tricky tracking, or a special wrapper that can decrement calls to "End" and call a true "End" when it reaches zero.
* The fact that an incoming message can have two paths - one to …

feat: add basic tracing for responses

---

impl/graphsync.go
responsemanager/client.go
responsemanager/responsemanager_test.go

this is now handled by the taskqueue which is outside of the
responsemanager so is not used here.

fix(responsemanager): remove unused maxInProcessRequests parameter

---

ipldutil/traverser.go
ipldutil/traverser_test.go

(see commit message)
Fixes #274.

ipldutil: simplify state synchronization, add docs

---

impl/graphsync_test.go
requestmanager/asyncloader/asyncloader.go
requestmanager/asyncloader/asyncloader_test.go
requestmanager/asyncloader/responsecache/responsecache.go
requestmanager/asyncloader/responsecache/responsecache_test.go
requestmanager/asyncloader/unverifiedblockstore/unverifiedblockstore.go
requestmanager/asyncloader/unverifiedblockstore/unverifiedblockstore_test.go
requestmanager/client.go
requestmanager/server.go
requestmanager/testloader/asyncloader.go
responsemanager/responsemanager_test.go
testutil/tracing.go

Trace synchronous responseMessage->loaderProcess->cacheProcess block storage and link those to asynchronous request->verifyBlock traces for the same blocks.
Closes: https://github.com/ipfs/go-graphsync/issues/317

feat(requestmanager): add tracing for response messages & block processing

---

testutil/tracing.go

Caught this working with tracing over in go-data-transfer. I'm not sure what causes ExportSpans to get called multiple times -- over a fixed number? some kind of context cancellation? Not sure. Anyway, if it does, we were losing spans.
Append span list rather than overwriting it on export.

Fix tracing span collection

---

impl/graphsync_test.go
messagequeue/builder.go
messagequeue/messagequeue.go
messagequeue/messagequeue_test.go
peermanager/peermessagemanager_test.go
requestmanager/requestmanager_test.go
responsemanager/client.go
responsemanager/queryexecutor/queryexecutor.go
responsemanager/queryexecutor/queryexecutor_test.go
responsemanager/responseassembler/responseBuilder.go
responsemanager/responseassembler/responseassembler.go
responsemanager/responseassembler/responseassembler_test.go
responsemanager/responsemanager_test.go
responsemanager/server.go

Trace the path of each out going response
There are three layers of traces here:
1. Tracking each message sent through the message queue
1. Produces: message -> sendMessage traces (where `message` encompasses the entire lifecycle of the message while `sendMessage` only covers the process of sending it over the wire)
2. Tracking each transaction in the ResponseAssembler
1. Produces: response -> transaction -> execute-> message-build (where transaction encompasses the the whole transaction, execute encompasses the whole call to AllocateAndBuildMessage time including waiting for memory to be allocated, and message-build includes only the time building the messageQueue message)
2. Links: message-build -> message span of the message the data ends up in
3. Tracking each block traversed in the …

Response message tracing

---

impl/graphsync_test.go
requestmanager/client.go
requestmanager/messages.go
requestmanager/server.go

This is just a consistency thing that I noticed while working on internal docs for the requestmanager code. In all other cases, the name of the public API in client.go matches a private version in server.go, just lower cased, and the message between them just has `Message` appended to the end. In this case, `ProcessResponses` maps to `processResponseMessage` which is also the name of the message that invokes it. So I've made the private `processResponses` and the message `processResponsesMessage`. The tracing span name, and some logging text also changes too to be consistent.

chore(requestmanager): rename processResponses internals for consistency

---

impl/graphsync_test.go
responsemanager/client.go
responsemanager/messages.go
responsemanager/responsemanager_test.go
responsemanager/server.go

Fixes: https://github.com/ipfs/go-graphsync/issues/318
Probably the most interesting part of this is seeing two separate messages do different things to a single response. In `TestPauseResumeViaUpdate` we see the first message linked to the start of a response and the second message get linked to the `processUpdate` span of the same response. Then in `TestCancellationQueryInProgress` we see the same thing but for an `abortRequest` triggered by the second message.
One possible change could be that we use this new `message` span as the parent to a `response` if no other parent gets inserted via the reuqestqueued context-modifying hook. So all `response` spans would have a `message` parent unless that hook is wired up by a consumer, as we do in `TestIncomingQuery` and I believe we'll be …

feat(responsemanager): trace full messages via links to responses

---

requestmanager/executor/executor.go
requestmanager/executor/executor_test.go

Currently, when the remote peer has a missing block, when we attempt to load that block on the requestor side and discover the remote was missing it, we still run block hooks as if we received it. This is very confusing behavior.
Don't run block hooks when loading a block errors on the requestor (the responder already avoids this)
Note: the vast majority of lines of new code in this PR are setting up a test.

Don't run hooks on blocks we didn't have

---

requestmanager/client.go
requestmanager/executor/executor.go
requestmanager/executor/executor_test.go
requestmanager/requestmanager_test.go
requestmanager/server.go

This PR has two small changes to remove the usage of do-not-send-cids in go-data-transfer
1. Removes usage of CID lists for graphsync's little known "pause/resume on the requestor side feature" (which works by cancelling and resending requests), moving instead to use do not send first blocks. This is almost surely not being used anyway but now its less unneccesarily memory intensive.
2. In order to be reliable about whether we're seeing blocks for the first time for go-data-transfer, we need to make sure we don't verify blocks after a request is canceled, so that when data transfer restarts, it seems the same results as from where it left off. This is probably what we should have done anyway... but it's a one line change in our cancel method.  See: …

Use do not send blocks for pause/resume & prevent processing of blocks on cancelled requests

---

message/v1/message.go

As per dission in https://github.com/ipfs/go-graphsync/pull/338, we are going
to be erroring on extension data that is not properly dag-cbor encoded from now
on

fix: clarify comments re dag-cbor extension data

---

go.mod
go.sum
responsemanager/responseassembler/responseBuilder.go

This is draft pending merging of https://github.com/ipld/go-ipld-prime/pull/346

fix: avoid double-encode for extension size estimation

---

graphsync.go
message/ipldbind/message.go
message/ipldbind/schema.ipldsch
message/message.go
message/v1/message.go
message/v1/message_test.go
message/v2/message.go
message/v2/message_test.go
messagequeue/messagequeue_test.go
network/libp2p_impl_test.go
peermanager/peermessagemanager_test.go
requestmanager/executor/executor_test.go
requestmanager/requestmanager_test.go
responsemanager/server.go

Closes: https://github.com/ipfs/go-graphsync/issues/345

feat(requesttype): introduce RequestType enum to replace cancel&update bools

---

message/ipldbind/message.go
message/ipldbind/schema.go
message/ipldbind/schema.ipldsch
message/v2/ipld_roundtrip_test.go
message/v2/message.go
message/v2/message_test.go

For:
1. Efficiency: compacting the noisy structures into tuples representations and making top-level components of a message optional.
2. Migrations: providing a secondary mechanism to lean on for versioning if we want a gentler upgrade path than libp2p protocol versioning.
Closes: https://github.com/ipfs/go-graphsync/issues/351
In terms of what this looks like, an example of an original message is in https://github.com/ipfs/go-graphsync/issues/351 and with this change the same data would look like (as dag-json):
```json
{
"gs1": {
"blk": [
[
{ "/": { "bytes": "AVUSIA" } },
{ "/": { "bytes": "QgTLmh40xfCOmyCqdgkOcAILtWwMo9OvcpbNEFilESiQ/tIYSI8ITY355INftUrQRf/ZNuO/cmGwQmxRNSoJeBbtdEgruQhLSn7YrcUX8zceDgQ0tRFiXNGkF5IkPczc/ogJSw" } }
],
[
{ "/": { "bytes": "AVUSIA" } },
{ "/": { "bytes": …
```

feat!(messagev2): tweak dag-cbor message schema

---

graphsync.go
impl/graphsync.go
impl/graphsync_test.go
requestmanager/client.go
requestmanager/requestmanager_test.go
requestmanager/server.go
responsemanager/client.go
responsemanager/messages.go
responsemanager/queryexecutor/queryexecutor.go
responsemanager/queryexecutor/queryexecutor_test.go
responsemanager/responsemanager_test.go
responsemanager/server.go
responsemanager/subscriber.go

Still working on this, it's not quite there yet, there's a problem with state management somewhere in the responsemanager that I'm having some difficulty figuring out.

feat(graphsync): unify req & resp Pause, Unpause & Cancel by RequestID

---

responsemanager/server.go

If request has finished selector traversal but is still sending blocks,
I think it should be possible to send updates. As a side effect, this
fixes our test race.
Logically, this makes sense, cause our external indicator that we're
done (completed response listener) has not been called.

fix(responsemanager): send update while completing

---

graphsync.go
impl/graphsync.go
impl/graphsync_test.go
requestmanager/client.go
requestmanager/messages.go
requestmanager/requestmanager_test.go
requestmanager/server.go
responsemanager/client.go
responsemanager/messages.go
responsemanager/queryexecutor/queryexecutor_test.go
responsemanager/responseassembler/responseBuilder.go
responsemanager/responseassembler/responseassembler.go
responsemanager/responsemanager_test.go
responsemanager/server.go

Closes: https://github.com/ipfs/go-graphsync/issues/348
WIP, figuring out the testing parts of this currently

feat: SendUpdates() API to send only extension data to via existing requests

---

requestmanager/server.go

Looks like one pointer type conversion slipped through -- discovered while testing with go-data-transfer

Fix regression from unify commands PR

---

README.md

It's been at least two years since the _checkout to `main`_ instructions were added. I think it's safe to say that folks have switched over their branches by now. It's also commonplace for the primary branch of a repo to be `main` instead of `master`, so calling out this change is likely moot.
Edit: this is the silliest, most nit-picky of PRs, so feel free to ignore and close.

Removes `main` branch callout.

---

requestmanager/server.go

Was missed in https://github.com/ipfs/go-graphsync/pull/356
This doesn't break anything obvious because the loader isn't used from the traverser's linksystem, and the traverser sets up defaults where the provided linksystem is missing them. But, we don't get certain things, like KnownReifiers, which are kind of important.

fix: wire up proper linksystem to traverser

---

messagequeue/messagequeue.go

This is a patch on top of 0.13.2. While debugging network disconnect issues in [Boost](https://github.com/filecoin-project/boost) during retrieval we discovered a leak in go-routines for graphsync. The issue is that a hard network disconnect may still result in the MessageQueue being restarted if there are messages the server is still attempting to send.
This change does not fully fix the issue but after multiple runs of force disconnecting 500 retrievals, we saw a 10x reduction in open goroutines. More robust handling for hard network disconnects may be warranted in the 0.14.x line, but that is also likely a non trivial effort. This gets us most of the way.
_The below were goroutine diffs between startup and after executing 500 forceful disconnects._
**Before**
**After**

fix: shutdown queue on publish error if not done

---

messagequeue/messagequeue.go

Port https://github.com/ipfs/go-graphsync/pull/414 to `release/v0.13.x` branch

fix: calling message queue Shutdown twice causes panic

---

impl/graphsync.go
impl/graphsync_test.go
messagequeue/messagequeue.go
messagequeue/messagequeue_test.go
peermanager/peermanager.go
peermanager/peermanager_test.go
peermanager/peermessagemanager.go
peermanager/peermessagemanager_test.go
responsemanager/responseassembler/responseassembler.go

This resolves the problem created by #412, without reverting the change that created a memory error.
Essentially the problem is the queue is shut down without being removed from the peer manager, which continues to send it messages, that have no effect. This change adds a hook so that the queue itself can notify the peer manager it's been shutdown.

Fix shutdown bug in #412

---

impl/graphsync_test.go
ipldutil/traverser.go
ipldutil/traverser_test.go
testutil/identity.go
testutil/testutil.go

Should probably add some tests in here.

fix: traverser should skip over identity CIDs

---

impl/graphsync_test.go
ipldutil/traverser.go
testutil/identity.go

It turns out that there are obscure cases where this matters, so we can't as easily just ignore identity CIDs. Specifically, classic online Filecoin deals that rely on Graphsync _and_ require identity CIDs be stored in the CARv1 that is used to calculate CommP must see the identity CID pass through the LinkSystem.
Unfortunately, the easiest way to deal with this is to send them over the wire as if they are a normal block; which happens to be the "safe" backward compatible way too. Less easy way would be to simulate it on both ends and not send them, but we'll take the easy path for now.
Extension of tests in here to make sure that the full DAG is transferred even in this case. Blockstore _must_ have identity CIDs in them, or be able to respond properly to them.

fix: partial revert of 1be7c1a20; make traverser process identity CIDs
